### ISSUE TITLE
Implement get one user

### ISSUE THREAD

**Issue by 1Popeye1** [1Popeye1/API-users#4]
the api should be on the form of `/{id}`

**Comment by 1Popeye1** [comment]
express => https://expressjs.com/en/starter/hello-world.html

sequelize => https://sequelize.org/master/index.html

npm, nodejs (import to know)

**Comment by niko-hs** [comment]
REST API : https://www.youtube.com/watch?v=-MTSQjw5DrM&ab_channel=Fireship

**Comment by niko-hs** [comment]
@1Popeye1 https://www.youtube.com/watch?v=-MTSQjw5DrM&ab_channel=Fireship
